<script type="text/javascript">
$(function(){
    var abas = $("#telacadastrar").tabs();
});
</script>
<h3 class="header">
    Depoimentos
</h3>

<div id="telacadastrar" title="Cadastrar Sala">
    <div id="telacadastro">
        <ul>
            <li><a href="#telasala">Inserir Sala</a></li>
        </ul>

        <div id="telasala">

            <form method="post" action="<?php echo $this->url(
                    array('controller' => 'Sala', 'action' => 'Index'), NULL, true); ?>" id="form1">
                <table width="100%">
                    <tr>
                        <td>Sala:</td> 
                        <td><input type="text" name="sala" id="sala" value="<?php echo $this->sala; ?>" /></td>
                    </tr>
                    <tr>
                        <td>Máxmo de Alunos:</td> 
                        <td><input type="text" name="maximo" id="maximo" value="<?php echo $this->maximo; ?>" /></td>
                    </tr>
                </table>
                <?php if(!isset($this->idsala)): ?>
                    <input type="submit" value="Cadastrar" id="btncadastrar" />
                <?php else: ?>
                    <input type="hidden" name="id" value="<?php echo $this->idsala; ?>" />
                    <input type="submit" value="Editar Dados" id="btncadastrar" />
                <?php endif; ?>
            </form>
        </div>
    </div>
</div>
 
<p id="resposta">
<?php echo $this->resp; ?>
</p>
<?php if(count($this->dados) > 0): ?>
<table class="dtgrid">
    <tr>
        <th>Sala</th>
        <th>Máximo de Alunos</th>
        <th>AÇÃO</th>
    </tr>
    <?php foreach($this->dados as $s): ?>
    <tr>
        <td><?php echo $s["sala"]; ?></td>
        <td><?php echo $s["maximo"]; ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller' => 'Sala', 'action' => 'Editar', 'params' => $s["idsala"])
                    , NULL, TRUE) ;?>">
            Editar
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>