<?php $this->setEscape('htmlentities');?>

<script type="text/javascript">
$(function(){
   
    var abas = $("#telacadastrar").tabs();
    
});
</script>
<h3 class="header">
    Palestras
</h3>


<form method="post" action="<?php echo $this->url(array('controller' => 'Palestra', 'action' => 'index'), NULL, true); ?>">
    Curso:
    <?php if(count($this->listaCurso) > 0): ?>
    <select name="curso" id="curso">
        <option value="0"></option>
        <?php foreach($this->listaCurso as $curso): ?>
        <option value="<?php echo $curso["idcurso"]; ?>" <?php echo ($this->curso == $curso["idcurso"])?"selected='selected'":""; ?>>
            <?php echo $curso["curso"]; ?>
        </option>
        <?php endforeach; ?>
    </select>
    
    <?php endif; ?>
    Status:
    <?php if(count($this->listastatus) > 0): ?>
    <select name="status" id="status">
        <?php foreach($this->listastatus as $opc): ?>
        <option value="<?php echo $opc[0]; ?>" <?php echo ($this->status == $opc[0])?"selected='selected'":""; ?>>
            <?php echo $opc[1]; ?>
        </option>
        <?php endforeach; ?>
    </select>
    
    <?php endif; ?>
    <input type="submit" value="Buscar" class="btn" />
</form>
<?php if(count($this->data) > 0): ?>
<table class="dtgrid">
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Contato</th>
        <th>Participou</th>
        <th>Data Cadastro</th>
        <th>AÇÃO</th>
    </tr>
    <?php foreach($this->data as $arq): ?>
        <tr>
            <td><?php echo $arq["nome"]; ?></td>
            <td><?php echo $arq["email"]; ?></td>
            <td><?php echo $arq["contato"]; ?></td>
            <td><?php echo ($arq["status"] == 1)?"Evento não realizado":(($arq["status"] == -1)?"Não veio":"Presente"); ?></td>
            <td><?php echo $arq["datacadastro"]; ?></td>
            <td>
                <?php if($this->util->validarPermissao($this->perfil, "Palestra", "excluir")): ?>
                 <a href="<?php echo $this->url(array('controller' => 'Palestra', 'action' => 'excluir',
                    'params' => $arq["idpalestra"]), null, true); ?>">
                     Excluir
                 </a>
                <?php endif; ?> 
                <?php if($this->util->validarPermissao($this->perfil, "Palestra", "edit")): ?>
                <a href="<?php echo $this->url(array('controller' => 'Palestra', 'action' => 'edit',
                    'params' => $arq["idpalestra"], "opc" => "0"), null, true); ?>">
                     Participou
                 </a>
                <?php endif; ?> 
                <?php if($this->util->validarPermissao($this->perfil, "Palestra", "edit")): ?>
                <a href="<?php echo $this->url(array('controller' => 'Palestra', 'action' => 'edit',
                    'params' => $arq["idpalestra"], "opc" => -1), null, true); ?>">
                     Não Veio
                 </a>
                <?php endif; ?> 
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<p id="resposta">
    <?php echo $this->resp; ?>
</p>
</div>