<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-1.8.0.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-ui-1.8.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-ui-pt.br.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.validate.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/additional-methods.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.printElement.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/maskedinput-1.1.2.pack.js"); ?>"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("estilo/redmond/jquery-ui.css"); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('estilo/estiloadm.css'); ?>" />
        <script type="text/javascript">
        $(function(){
            $("#conteudo").hide();
            $(":submit").button();
            $(".btn").button();
            if($("#resposta").text().trim() != ""){
                $("#resposta").hide().attr("title", "Tela de Mensagens");
                $("#resposta").dialog({
                    modal : true
                });
            }
        });
        </script>
    </head>
    <body>
        
        
            
            <header id="topo">
                
			
                <h1>COTI INFORMÁTICA - PAINEL ADMINISTRATIVO</h1>
                
			</header>		
			
                <nav id="menu">
                    <?php if($this->util->validarPermissao($this->perfil, "Area", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Area', 'action' => 'index'), NULL, true); ?>">AREA</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Curso", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Curso', 'action' => 'index'), NULL, true); ?>">CURSOS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Turma", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Turma', 'action' => 'index'), NULL, true); ?>">TURMAS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Aluno", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Aluno', 'action' => 'index'), NULL, true); ?>">ALUNOS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Depoimento", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Depoimento', 'action' => 'index'), NULL, true); ?>">DEPOIMENTOS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Usuario", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Usuario', 'action' => 'index'), NULL, true); ?>">USUÁRIOS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Chamada", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Chamada', 'action' => 'index'), NULL, true); ?>">CHAMADAS</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Newsletter", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Newsletter', 'action' => 'index')); ?>">NEWSLETTER</a>
                    <?php endif; ?>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Contato", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Contato', 'action' => 'index')); ?>">CONTATO</a>
                    <?php endif; ?>
                        
                    <?php if($this->util->validarPermissao($this->perfil, "Arquivo", "index")): ?>
                        <!--<a href="<?php //echo $this->url(array('controller' => 'Arquivo', 'action' => 'index')); ?>">ARQUIVOS</a>-->
                    <?php endif; ?>
                       
                    <?php if($this->util->validarPermissao($this->perfil, "Promocao", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Promocao', 'action' => 'index')); ?>">PROMOÇÃO</a>
                    <?php endif; ?>
                        
                    <?php if($this->util->validarPermissao($this->perfil, "Campanha", "index")): ?>
                        <!--<a href="<?php //echo $this->url(array('controller' => 'Campanha', 'action' => 'index')); ?>">
                            CAMPANHA</a>-->
                    <?php endif; ?>
                        
                    <?php if($this->util->validarPermissao($this->perfil, "Reserva", "index")): ?>
                    <a href="<?php echo $this->url(array('controller' => 'Reserva', 'action' => 'index')); ?>">
                        RESERVA</a>
                    <?php endif; ?>
                        
                    <?php if($this->util->validarPermissao($this->perfil, "Relatorio", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Relatorio', 'action' => 'index')); ?>">RELATÓRIOS</a>
                    <?php endif; ?>
                        
                    
                    
                </nav>
                                
                <p class="imgloader" style="margin: auto"><img src="<?php echo $this->baseUrl('img/ajax-loader.gif'); ?>"></p>
            
			
            <div id="container">
			
			<span class="boasvindas"> 
                    <br><br>Seja Bem vindo 
                        <?php
                    $session = new Zend_Session_Namespace();
                    if(isset($session->login)){
                        echo $session->login;
                    }else{
                        echo "Visitante";
                    }
                ?>
                    -> 
                    <a href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'painel'), NULL, true); ?>">Home</a>
                    
                    <?php if($this->util->validarPermissao($this->perfil, "Palestra", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Palestra', 'action' => 'index')); ?>">Palestras</a>
                    <?php endif; ?>
                        
                    <?php if($this->util->validarPermissao($this->perfil, "Curriculo", "index")): ?>
                        <a href="<?php echo $this->url(array('controller' => 'Curriculo', 'action' => 'index')); ?>">Currículos</a>
                    <?php endif; ?>
                        
                    <a href="<?php echo $this->url(array('controller' => 'Usuario', 'action' => 'sair'), NULL, true); ?>">Sair</a>
					</span>
			
            <section id="conteudo">
                <?php echo $this->layout()->content; ?>
            </section>
            
            <script type="text/javascript">
                $(function(){
                    $(".imgloader").hide();
                    $("#conteudo").show();
                });
            </script>
        </div>
        
    </body>
</html>
